version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  # Root workspace dependencies
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    groups:
      development-dependencies:
        dependency-type: development
      production-dependencies:
        dependency-type: production

  # Client app dependencies
  - package-ecosystem: npm
    directory: "/apps/client "
    schedule:
      interval: daily
    groups:
      nextjs:
        patterns:
          - "next*"
          - "@next/*"
      react:
        patterns:
          - "react*"
          - "@types/react*"

  # API app dependencies  
  - package-ecosystem: npm
    directory: /apps/api
    schedule:
      interval: daily
    groups:
      hono:
        patterns:
          - "hono*"
      thirdweb:
        patterns:
          - "thirdweb*"

