services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
      target: development
    container_name: launcher-api
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./apps/api:/app
      - /app/node_modules
    restart: unless-stopped

  client:
    build:
      context: "apps/client "
      dockerfile: Dockerfile
    container_name: launcher-client
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - type: bind
        source: "apps/client "
        target: /app
      - /app/node_modules
    restart: unless-stopped
    depends_on:
      - api 